services:
  redis:
    healthcheck:
      test: redis-cli ping || exit 1
    hostname: redis
    image: docker.io/valkey/valkey:9@sha256:70739f85ad2ee01a726a965584a0f94895f01b0c60b3cc8b0aeef11eaa6888cf
    networks:
      - redis_net
    restart: unless-stopped

networks:
  redis_net:
    internal: true
