services:
  db:
    image: mariadb:11.8
    env_file: .env.db
    volumes:
      - ./gitea/mysql:/var/lib/mysql

  gitea:
    image: gitea/gitea:1.25
    depends_on:
      - db
    env_file: .env.gitea
    volumes:
      - D:\Users\tarun\git-ssh-server\gitea\data:/data
    ports:
      - "222:22"

  master:
    image: chrislusf/seaweedfs
    command: master -ip=master -ip.bind=0.0.0.0 -metricsPort=9324
    expose:
      - "9333"
      - "19333"
      - "9324"
    volumes:
      - ./seaweedfs/master:/data
    restart: unless-stopped

  volume:
    image: chrislusf/seaweedfs
    command: volume -ip=volume -master="master:9333" -ip.bind=0.0.0.0 -port=8080 -metricsPort=9325
    depends_on:
      - master
    expose:
      - "8080"
      - "18080"
      - "9325"
    volumes:
      - D:\Users\tarun\git-ssh-server\seaweedfs\data:/data
    restart: unless-stopped

  filer:
    image: chrislusf/seaweedfs
    command: filer -ip=filer -master="master:9333" -ip.bind=0.0.0.0 -metricsPort=9326
    depends_on:
      - master
      - volume
    expose:
      - "8888"
      - "18888"
      - "9326"
    volumes:
      - ./seaweedfs/filer:/data
    restart: unless-stopped

  s3:
    image: chrislusf/seaweedfs
    command: s3 -filer="filer:8888" -ip.bind=0.0.0.0 -metricsPort=9327
    depends_on:
      - master
      - volume
      - filer
    env_file: .env.s3
    expose:
      - "8333"
      - "9327"
    restart: unless-stopped
  
  nginx:
    image: nginx:1.29-alpine
    depends_on:
      - gitea
      - filer
      - s3
    ports:
      - "9443:9443"
      - "10443:10443"
      - "11443:11443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
