#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER "$GITEA_DB_USERNAME" WITH PASSWORD '$GITEA_DB_PASSWORD';
    CREATE DATABASE "$GITEA_DB_DATABASE" OWNER "$GITEA_DB_USERNAME";

EOSQL
