services:
  ddgs-mcp-container:
    hostname: ddgs-mcp-container
    image: docker.io/tarunsrisai/ddgs-mcp-container:latest@sha256:cc887aff625887c6939ca3d9ebd4a86e6422e3182bb5480e7e3f8192e6b7f814
    networks:
      - ddgs_net
      - nginx_net
    restart: unless-stopped

  llama-server:
    command: -hf ${HF_MODEL_ID} --alias ${HF_MODEL_ALIAS} -c ${CONTEXT_SIZE} -ngl ${GPU_LAYERS} --temp ${TEMPERATURE} --top-p ${TOP_P}
    depends_on:
      - ddgs-mcp-container
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    environment:
      HF_HOME: /models
    hostname: llama-server
    image: ghcr.io/ggml-org/llama.cpp:server-cuda@sha256:c50a38601c8bbb6dcb2fdbe60ee336faea7c7c7e11a1d5a6396993783617d911
    networks:
      - nginx_net
      - llama_net
    restart: unless-stopped
    volumes:
      - ${MODELS_PATH}:/models

networks:
  llama_net:
    internal: true
  ddgs_net:
