include:
  - ../redis/compose.include.yaml
  - ../postgres/compose.include.yaml

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    hostname: immich-server
    volumes:
      - ${UPLOAD_LOCATION}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    healthcheck:
      disable: false
    restart: unless-stopped
