include:
  - ../postgres/compose.include.yaml

services:
  gitea:
    image: docker.io/gitea/gitea:1.26
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ${GITEA_DATA}:/data
    ports:
      - "2222:22"
    restart: unless-stopped
